import { Box } from 'components/Box';
import Head from 'next/head';
import { RecoilRoot } from 'recoil';
import { DarkModeToggleBtn } from '../components/DarkModeToggleBtn';
import { SearchAside } from './components/SearchAside';
import { SearchHeader } from './components/SearchHeader';
import { SearchMain } from './components/SearchMain';
import { DummyData, dummyData } from './dummy';

export default function Home({ probs, sols, user }: DummyData) {
  return (
    <RecoilRoot>
      <Head>
        <title>codeisneverodd</title>
        <meta name="description" content="Generated by codeisneverodd's starter kit" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchHeader />
      <div className="mt-20 flex w-full">
        <SearchMain>
          <SearchMain.Result />
        </SearchMain>
        <SearchAside>
          <SearchAside.SelectProbCard />
          <SearchAside.AdCard />
        </SearchAside>
      </div>
      <Box className="fixed bottom-0 flex w-full justify-between">
        <h1 className="text-3xl">Dev Tool</h1>
        <DarkModeToggleBtn />
      </Box>
    </RecoilRoot>
  );
}

export async function getStaticProps() {
  return {
    props: dummyData,
  };
}
