import { Box } from 'components';
import Head from 'next/head';
import { tw } from 'utils/tailwindMerge';
import { DarkModeToggleBtn } from './components/DarkModeToggleBtn';

export default function Home() {
  return (
    <>
      <Head>
        <title>codeisneverodd</title>
        <meta name="description" content="Generated by codeisneverodd's starter kit" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-4 pt-8">
        <Box className="mt-5 flex justify-between">
          <h1 className="text-3xl">홈</h1>
          <DarkModeToggleBtn />
        </Box>
        <Box className="mt-5">하이</Box>
      </main>
    </>
  );
}
